config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :properties
  resources :sellers
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
    }
  get 'properties/index'
  root 'properties#index'

  # root 'buyers#index'
  get '/search' => 'buyers#search'
 
  get '/filter' => 'buyers#filter'
  get '/search' => 'properties#search'
  get '/buyers/index' => 'buyers#index'
  get '/buyers/new'  => 'buyers#new'
  get '/sellers/index' => 'sellers#index'
  get '/sellers/new'  => 'sellers#new'
  get 'buyers/about' => 'buyers#about'
  get 'buyers/contact' => 'buyers#contact'
  get 'store/index' => 'store#index'
  get 'store/new' => 'store#new'
  get 'properties/edit' => 'properties#edit'
  post "users/edit" 

   resources :properties do
     resources :likes
  
end

resources :properties do
  resources :unlikes
end

  devise_scope :user do  
   get '/users/sign_out' => 'devise/sessions#destroy'     
 end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/seller.rb
class Seller < ApplicationRecord
	belongs_to :property
end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController
	def index
		@properties = current_user.properties
	end

	def new 
	end

	def show
	end
end

app/views/sellers/index.html.erb
<% if current_user.role == 'Seller' %>
<h1 style= "color: black;"> Seller </h1>
<%= link_to "Profile",sellers_new_path, class:"btn btn-primary"%> | 
<%= link_to "Create New Property", new_property_path, class: "btn btn-primary" %> |
<%= link_to "Property", properties_path, class: "btn btn-primary" %> |
<%= link_to "My Property", properties_path(my_property: true), class: "btn btn-primary" %>
<div class="row"> 
    <% if @properties.present? %>
    <% @properties.each do |p|%>
    <div class="col-md-3 my-2">
    <div class="card">
        <div class="card-body">
            <% if p.avatar.attached? %>
            <%= image_tag p.avatar, height: "200px" , width: "90%" %>
            <% end %>
            <h5 style="color :black;" class="card-title"><%= p.title%></h5>
            <h6 style="color :black;"> <p class="card-text">
             <%= p.location %> <br>
             <%= p.rate %><br>
             <%= p.area %>
         </p>
     </h6>
    </div>
     <div class="card">
        <%= link_to "View", property_path(p), class:"btn btn-primary"%>
    </div>
</div>
</div>
<% end %>
<% end %>
<% else %>
<center>
    You are at wrong section
    <% end %>

app/views/sellers/new.html.erb
<center>
<% if current_user.role == 'Seller' %>
<h1 style="color :black;">  My profile </h1>
<h4 style="color :black;"> <%= current_user.name %> <br>
<%= current_user.email %> <br>
<%= current_user.contact_no %> <br>
<%= current_user.address %> </h4>
<% else %>
<center>
<h1 style="color: black;"> you are at wrong section </h1>
<% end %>
</center>
<%= link_to 'Back' ,sellers_path %>

app/views/sellers/show.html.erb
<% if current_user.role == 'Seller' %>
<h1 style= "color: black;"> Seller </h1>
<%= link_to "Profile",buyers_new_path, class:"btn btn-primary"%> | 
<%= link_to "Create New Property", new_property_path, class: "btn btn-primary" %> |
<%= link_to "Property", properties_path, class: "btn btn-primary" %> |
<%= link_to "My Property", properties_path(my_property: true), class: "btn btn-primary" %>

<% else %>
<center>
<h1 style="color: black;"> you are at wrong section </h1>
<% end %>