config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :properties
  resources :sellers
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
    }
  get 'properties/index'
  root 'properties#index'

  # root 'buyers#index'
  get '/search' => 'buyers#search'
 
  get '/filter' => 'buyers#filter'
  get '/search' => 'properties#search'
  get '/buyers/index' => 'buyers#index'
  get '/buyers/new'  => 'buyers#new'
  get '/sellers/index' => 'sellers#index'
  get '/sellers/new'  => 'sellers#new'
  get 'buyers/about' => 'buyers#about'
  get 'buyers/contact' => 'buyers#contact'
  get 'store/index' => 'store#index'
  get 'store/new' => 'store#new'
  get 'properties/edit' => 'properties#edit'
  post "users/edit" 

   resources :properties do
     resources :likes
  
end

resources :properties do
  resources :unlikes
end

  devise_scope :user do  
   get '/users/sign_out' => 'devise/sessions#destroy'     
 end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/property.rb
class Property < ApplicationRecord
    has_one_attached :avatar
    has_one_attached :image
    has_many :likes, dependent: :destroy
    has_many :buyers
    belongs_to :user
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_property, only: [:show, :edit, :update, :destroy]
# load_and_authorize_resource

  # GET /properties or /properties.json
  def index
    
    if params[:location].present?
      @properties = Property.where(location: params[:location])
    elsif params[:my_property]
      @properties = current_user.properties
    else
      @properties = Property.all
    end
  end

  # GET /properties/1 or /properties/1.json
  def show
    # @property = Property.find_by(@property)
    @likes = @property.likes
  end

  # def like
  #   UserMailer.with(user: current_user,user: @user).post_created.deliver_now
  # end

  def search
    if params[:search].blank?
      redirect_to(properties_path, alert: "Enter Valid Name!") and return
    else
       # keyword = params[:search]
       @properties = Property.where(["title LIKE ?", "%#{params[:search]}%" ])
     end
  end
  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties or /properties.json
  def create
    @property = Property.new(property_params)

    respond_to do |format|
      if @property.save
        # UserMailer.welcome_email(@user).deliver_later
        format.html { redirect_to property_url(@property), notice: "Property was successfully created." }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1 or /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to property_url(@property), notice: "Property was successfully updated." }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1 or /properties/1.json
  def destroy
    @property.destroy

    respond_to do |format|
      format.html { redirect_to properties_url, notice: "Property was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_property
      @property = Property.find(params[:id])        
  end

    # Only allow a list of trusted parameters through.
  def property_params
    params.require(:property).permit(:title, :property_type, :location, :rate, :area, :avatar, :description, :search, :user_id)
  end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_form.html.erb
<%= bootstrap_form_with(model: property, local: true) do |form| %>
  <% if property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% property.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.text_field :rate %>
  </div>

  <div class="field">
    <%= form.text_field :area %>
  </div>

  <div class="field">
    <%= form.text_field :description %>
  </div>

   <div class="field">
    <%= form.number_field :user_id, value: current_user.id, type: :hidden %>
  </div>

  <div class="field">
    <%= form.file_field :avatar %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/properties/edit.html.erb
<h1>Editing Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', property_path %>

app/views/properties/index.html.erb
<p id="notice"><%= notice %></p>
  <h1 style= "color: black;"> Properties </h1>
  <div class="row mx-0">
    <% @properties.each do |property| %>
    <div class="col-md-3 my-2">
    <div class="card">
      <div class="card-body">
        <% if property.avatar.attached? %>
        <%= image_tag property.avatar, height: "150px", width: "100%" %>
        <% end %>
        <h5 style="color :black;" class="card-title"><%= property.title%></h5>
        <h6 style="color :black;"> <p class="card-text">
          <%= property.location %> <br>
          <%= property.rate %><br>
          <%= property.area %>
          <%= property.description %>
        </p>
      </h6>
    </div>
      <% if current_user.role == 'Seller' %>
      <%= link_to 'Show', property %>
      <%= link_to 'Edit', edit_property_path(property) %>
      <%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% else %>
      <%= link_to 'Show', property %>
      <% end %>
    </div>
  </div>
  <% end %>
  <br>
  <% if current_user.role == 'Seller' %>
  <%= link_to 'New Property', new_property_path %>
  <% else %>
  <%= link_to 'Back' ,buyers_index_path %>
  <% end %>

  <% if current_user.role == 'Seller' %>
  <%= link_to 'Back' ,sellers_path %>
  <% end %>

app/views/properties/like.html.erb
<div style="float: left;">
  <%= property.likes.count %>
  <% like = current_user.likes.find_by(property: property) %> 
  <% if like.nil? %>
  <%=  link_to likes_path({ like: { property_id: property.id } }), method: :property do %>
  <%= image_tag "like-inactive.png", style: "height: 40px;" %>
  <% end %>
  <% else %>
  <%=  link_to  like_path(like), method: :delete do %>
  <%= image_tag "like-active.png", style: "height: 40px;" %>
  <% end %>
  <% end %>
</div>

app/views/properties/new.html.erb
<h1>New Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Back', sellers_path %>

app/views/properties/search.html.erb
<h1>Properties</h1>
<table>
  <thead>
    <tr>
      <table id="student" border="2" layout= "fixed" width=" 60%"  >
        <colgroup>
        <col style="width: 10%" />
        <col style="width: 10%" />
        <col style="width: 10%" />
        <col style="width: 10%" />
        <col style="width: 20%" />
      <th>Title</th>
      <th>Location</th>
      <th>Rate</th>
      <th>Area</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <table id="student" border="1" layout= "fixed" width=" 60%"  >
        <colgroup>
        <col style="width: 10%" />
        <col style="width: 10%" />
        <col style="width: 10%" />
        <col style="width: 10%" />
        <col style="width: 20%" />

        <td><%= property.title %></td>
        <td><%= property.location %></td>
        <td><%= property.rate %></td>
        <td><%= property.area %></td>
        <td><%= link_to 'Show', property %></td>
        
        </tr>
    <% end %>
  </tbody>
</table>

app/views/properties/show.html.erb
 <div class="container">
  <p id="notice"><%= notice %></p>
  <strong>Image:</strong> <br>
  <%= image_tag @property.avatar, width: "300px" if @property.avatar.attached?  %> 


  <p> 
    <strong>Title:</strong>
    <%= @property.title %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= @property.location %>
  </p>

  <p>
    <strong>Rate:</strong>
    <%= @property.rate %>
  </p>

  <p>
    <strong>Area:</strong>
    <%= @property.area %>
  </p>


  <p>
    <strong>Description:</strong>
    <%= @property.description %>
  </p>

  <% if current_user.Buyer? %>
  <%= link_to 'Back' , buyers_index_path %>
  <%= button_to 'Interest', property_likes_path(@property), method: :property %>
  <% else %>
  <%= link_to 'Back' , sellers_path %>
  <%= link_to 'Edit' , edit_property_path(@property) %>
  <% end %>


</div>
<div class='col-md-6'>
  <p><%= @property.likes.count %> <%= (@property.likes.count) == 1 ? 'Like' : 'Likes'%></p>
</div>
</div> 