config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :properties
  resources :sellers
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
    }
  get 'properties/index'
  root 'properties#index'

  # root 'buyers#index'
  get '/search' => 'buyers#search'
 
  get '/filter' => 'buyers#filter'
  get '/search' => 'properties#search'
  get '/buyers/index' => 'buyers#index'
  get '/buyers/new'  => 'buyers#new'
  get '/sellers/index' => 'sellers#index'
  get '/sellers/new'  => 'sellers#new'
  get 'buyers/about' => 'buyers#about'
  get 'buyers/contact' => 'buyers#contact'
  get 'store/index' => 'store#index'
  get 'store/new' => 'store#new'
  get 'properties/edit' => 'properties#edit'
  post "users/edit" 

   resources :properties do
     resources :likes
  
end

resources :properties do
  resources :unlikes
end

  devise_scope :user do  
   get '/users/sign_out' => 'devise/sessions#destroy'     
 end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/buyer.rb
class Buyer < ApplicationRecord
	belongs_to :property
end

app/controllers/buyers_controller.rb
class BuyersController < ApplicationController
	def index
		@properties = Property.all
	end
	
	def new
	end

	def search
	    if params[:search].blank?
	      redirect_to(buyers_new_path, alert: "Enter Valid Name!") and return
	    else
	       keyword = params[:search]
	       @properties = Property.where(["title LIKE ?", "%#{keyword}%" ])
	    end
	end

	def filter
		if params[:title].blank?
	      redirect_to(properties_path, alert: "Enter Valid Name!") and return
	    else
	       keyword = params[:title]
	       @properties = Property.where(["title LIKE ? OR location LIKE ? OR rate LIKE ?", "%#{keyword}%", "%#{keyword}%", "%#{keyword}%"])
	  end
	end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_buyer
      @buyer = Buyer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def buyer_params
      params.require(:buyer).permit(:title, :_type, :location, :name, :rate, :area, :avatar, :search)
    end
end

app/views/buyers/_filter_modal.html.erb
<div id="property_filter_modal"  class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <%= form_tag(filter_path, :method => "get") do %>  
        <div class="modal-header">
          <h5 class="modal-title">Search Property</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          <h4 class="modal-title popup-modal-title"></h4>
        </div>

        <div class="modal-body popup-modal-body">       
          <%= text_field_tag :title, params[:search], placeholder: 'Search' %>

        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <%= button_tag "Search", :class => 'btn btn-primary',:title => nil %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/buyers/about.html.erb
<div class="tab-content">

  <div role="tabpanel" class="tab-pane active animated fadeInLeft" id="ABOUT-REAL-ESTATE">
    <div class="clearfix"></div>
    <div class="vspace"></div>
    <div class="vspace"></div>
    <div class="container">
      <div class="col-sm-8">
        <p style="font-size:30px" ; style=" color: black;">ABOUT REAL ESTATE</p>
        <p class="about-para"><b> Real Estate vertical of Garg Group a 50 years old group, having diversified interests in publication, education and real estate. LandCraft was founded in the year 2006 and being a part of Garg Group it has been laid down on solid foundation.</b></p>
        <p class="about-head"><b>REASONS WE ARE BUILT ON SOLID FOUNDATION</b></p>
        <ul class="about-list">
          <li>&#9642;   Part of Diversified Group</li>
          <li>&#9642;   Our Founder's Philosophy: "Niyat Gail Barkat"</li>
          <li>&#9642;   All our structural designs are approved by IIT Delhi.</li>
          <li>&#9642;   In-house lab and strict Quality Control as per ISO Standards.</li>
          <li>&#9642;   Use of latest technologies like Mivan Shuttering</li>
        </ul>
        <p class="about-para"><b>Given the number of prestigious projects the company has delivered and the several more it has been signed up for, LandCraft looks to the future with confidence, with plans afoot to aggressively expand beyond Delhi and the NCR.</b></p>
      </div>
      <div class="clearfix"></div>
      <div class="vspace"></div>
      <div class="vspace"></div>
    </div>


  </div>
  <div class="tabpanel">

    <header>
     <p style="font-size:10px"
     <div class="container border-bottom">
      <ul class="contact-info">
        <li> <a href="tel:8585900157"> <x>Sales</x> +91 8585900157</a> </li>
        
        <li> <a href="tel:1204185000"><x>Office</x> 91-731-4984840</a> </li>

        <li> <a href="https://www.bestpeers.com/">info@bestpeers.in </a> </li> 
      </ul>
    </p>
  </header>
  <div class="tab-content">


    <footer>
      <nav class="navbar navbar-dark bg-light justify-content-between">
        <div class="link-list style-left">
          <div class="link-list style-right">
            <div class="copyright">
              <div class="container">
                <div class="col-sm-12 col-md-6 col-xs-12">
                  <p>Copyright &copy; 2020, Landcraft Developers Pvt. Ltd</p>
                </div>
                <div class="col-sm-12 col-md-6 col-xs-12">
                 <p class="text-right"><a href="http://www.acetz.com" target="_blank">Powered by: <x>Bestpeers Infosystem Private Limited</x></a></p>
               </div>
             </div>
           </nav>
    </footer>

    <% if current_user.role == 'Seller' %>
    <%= link_to 'Back', sellers_path %>
    <% else %>
    <%= link_to 'Back' ,buyers_index_path %>
    <% end %>

app/views/buyers/contact.html.erb
<div class="break">
  <div class="bread-section">
    <div class="container">
      <div class="news-marquee">
        <p>
          <span>
            <h1>
            </div>
            <p style="font-size:30px"; style="color: black;"> News </p>
          </h1>
          <marquee>
            <a href="https://www.ashianahousing.com/real-estate-blog/5-reasons-why-real-estate-is-your-safest-best-long-term-investment-option/" target="_blank">Top 10 Reasons Why Investing in Properties on Real Estate is a Good Idea</a> 
          </a> 
        </marquee>
      </span>
    </p>
  </div>

</div>
</div>


<section>
 <div class="panel panel-default">
   <div class="panel-heading">
     <h5 class="panel-title contact-heading">BESTPEERS INFOSYSTEM PVT. LTD.</h5>
   </div>
   <div class="panel-body">
     <address>
      Bestpeers InfoSystem Pvt. Ltd. <BR> 142-A, First Floor, New IT Park Building, <br>Electronic Complex, Pardesipura, <br> Indore, Madhya Pradesh 452010
    </address>
    <a href="#">Phone: &nbsp;<i class="flaticon-telephone-1"></i> +91-120-4185000</a><br>
    <a href="#">Fax:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <i class="flaticon-telephone-1"></i>  +91-120-4185005</a><br>
    <a href="#">Email:&nbsp;&nbsp; <i class="flaticon-back"></i> info@bestpeers.in</a>
    <div class="vspace"></div>
    <div class="contactmap-btn">
    </div>
  </div>
</div>
</section>

<% if current_user.role == 'Seller' %>
<%= link_to 'Back', sellers_path %>
<% else %>
<%= link_to 'Back' ,buyers_index_path %>
<% end %>

app/views/buyers/filter.html.erb
<div class = "container"> 
<div class="row">
    <% if @properties.present? %>
    <% @properties.each do |p|%>
     <div class="card" style="width: 18rem; background-color: #cedae9;">
     <div class="card-body">
     <% if p.avatar.attached? %>
      <%= image_tag p.avatar, height: "150px" %>
    <% end %>
   <h5 class="card-title"><%= p.title%></h5>
    <p class="card-text">
        <%= p.location %> <br>
        <%= p.rate %><br>
        <%= p.area %>
    </p>
    <p> Created by: <%= p.user.name.capitalize %> </p>
    <%= link_to "View", property_path(p), class:"btn btn-primary"%>
    </div>
    </div>
  <% end %>
<% end %>
</div>
</div>

<%= link_to 'Back' ,buyers_index_path %>

app/views/buyers/index.html.erb
<% if current_user.role == "Buyer" %>
<div class= "contanier my-3">
  <p id="notice"><%= notice %></p>
  <h1 style="color:black;">Buyers</h1>
  <%= link_to "Profile",buyers_new_path, class:"btn btn-primary"%> 
  <a href='javascript:void(0)' class='property_filter', search_path>Filter</a>
  <div class="row mx-0">
      <% if @properties.present? %>
      <% @properties.each do |p|%>
      <div class="col-md-3 my-2">
      <div class="card">
       <div class="card-body">
         <% if p.avatar.attached? %>
         <%= image_tag p.avatar, height: "200px" , width: "100%"%>
         <% end %>
         <h5 style="color :black;" class="card-title"><%= p.title%></h5>
         <h6 style="color :black;"> <p class="card-text">
          <%= p.location %> <br>
          <%= p.rate %><br>
          <%= p.area %>
        </p>
        <p> Created by: <%= p.user.name.capitalize %> </p>
        <%= link_to "View", property_path(p), class:"btn btn-primary"%>
      </h6>
    </div>
    </div>
  </div>
  <% end %>
  <% end %>
</div>
<% else %>
<center>
  <h1 style="color: black;"> you are at wrong section </h1>
  <% end %>

  <%= render partial: 'buyers/filter_modal' %>

app/views/buyers/new.html.erb
<center>
<h1 style="color :black;">  My profile </h1>
<h4 style="color :black;"> <%= current_user.name %> <br>
<%= current_user.email %> <br>
<%= current_user.contact_no %> <br>
<%= current_user.address %> </h4>
</center>  
<%= link_to 'Back' ,buyers_index_path %>

app/views/buyers/search.html.erb
<div class = "container"> 
<div class="row">
    <%# if @properties.present? %>
    <% @properties.each do |p|%>
     <div class="card" style="width: 18rem; background-color: #cedae9;">
     <div class="card-body">
     <% if p.avatar.attached? %>
      <%= image_tag p.avatar, height: "150px" %>
    <% end %>
   <h5 class="card-title"><%= p.title%></h5>
    <p class="card-text">
        <%= p.location %> <br>
        <%= p.rate %><br>
        <%= p.area %>
    </p>
    <p> Created by: <%= p.user.name.capitalize %> </p>
    <%= link_to "View", property_path(p), class:"btn btn-primary"%>
    </div>
    </div>
  
<% end %>
</div>
</div>
<% if current_user.role == 'Seller' %>
<%= link_to 'Back', sellers_path %>
<% else %>
<%= link_to 'Back' ,buyers_index_path %>
<% end %>

app/views/buyers/show.html.erb
<div class = "container">
<p id="notice"><%= notice %></p>
  </p>
<h1>Properties</h1>

<table>
  <thead>
    <tr>
      <table id="buyer" border="2" layout= "fixed" width=" 50%"  >
        <colgroup>
        <col style="width: 10%" />
        <col style="width: 10%" />
        <col style="width: 20%" />
        <col style="width: 20%" />
        <col style="width: 20%" />
      <th>Title</th>
      <th>Property type</th>
      <th>Location</th>
      <th>Rate</th>
      <th>Area</th>
      <th colspan="5"></th>
    </tr>
  </thead>
  <div>
    
  </div>
  <tbody>
    <% Property.all.each do |property| %>
      <tr>
        <table id="buyer" border="2" layout= "fixed" width=" 50%"  >
        <colgroup>
        <col style="width: 10%" />
        <col style="width: 10%" />
        <col style="width: 20%" />
        <col style="width: 20%" />
        <col style="width: 20%" />

        <td><%= property.title %></td>
        <td><%= property.property_type %></td>
        <td><%= property.location %></td>
        <td><%= property.rate %></td>
        <td><%= property.area %></td>
        <td><%= link_to 'Show', property %></td>
    
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</div>